GET  https://localhost:5001/api/abp/application-configuration HTTP/1.1 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MTAyMzEwOTMsImV4cCI6MTYxMDIzNDY5MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Ik5nQXNwbmV0Y29yZS5IdHRwQXBpLkhvc3RBUEkiLCJjbGllbnRfaWQiOiJJRFNfQ0xJRU5UX0FwcCIsInN1YiI6IjgwZmJlYmM1LTE4OWQtNGI1ZS1iNzYwLWM1YTQ1NzdjMzI5NiIsImF1dGhfdGltZSI6MTYxMDIzMTA5MywiaWRwIjoibG9jYWwiLCJqdGkiOiJEQjYxQ0YxMjYyNTg5QjRDRkJDQzIzODVBRDY1RUYyNiIsImlhdCI6MTYxMDIzMTA5Mywic2NvcGUiOlsiTmdBc3BuZXRjb3JlLkh0dHBBcGkuSG9zdEFQSSIsIm9wZW5pZCIsInByb2ZpbGUiXSwiYW1yIjpbInB3ZCJdfQ.RJ97SLA0oJnyd2fU56r4tsWBGB_neKUGJp5NZWoXmlJcQpDp55GEZJEUJ2ojNJwi48m7NfwROTKMaKzY3iluNMfvp68PM1fp2ATZZXRmL2-zOqOERPufWVRILRt_Kyu6L8i0wDPlWuKiRBvBzYiy7aOOXOoX6cpL9PRwtY13Ws7vWCJm8rDGQDDiHDTlUsNalevoxOFQie1sWtI6wZrGBg7PqIVVqFYpXEGS-jgrvArUTV7QRRsZ5F0LlBSuuRivSXXLR_7OeWn_bz7g1ygEkpTOMZYGrsh5p90A50D9YNPIPPoV5F3hSfFp8VLpeQOyYUyPAkueQ-2gSq5yCMJJmg
