GET  https://localhost:5001/api/abp/application-configuration HTTP/1.1 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2MTAyMjkyMDEsImV4cCI6MTYxMDIzMjgwMSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Ik5nQXNwbmV0Y29yZS5IdHRwQXBpLkhvc3RBUEkiLCJjbGllbnRfaWQiOiJJRFNfQ0xJRU5UX0FwcCIsInN1YiI6IjgwZmJlYmM1LTE4OWQtNGI1ZS1iNzYwLWM1YTQ1NzdjMzI5NiIsImF1dGhfdGltZSI6MTYxMDIyOTIwMSwiaWRwIjoibG9jYWwiLCJqdGkiOiJFRDcyMzcwODcxODBDREZGRDJBODBEOEM3Qjg5MDA0NSIsImlhdCI6MTYxMDIyOTIwMSwic2NvcGUiOlsiTmdBc3BuZXRjb3JlLkh0dHBBcGkuSG9zdEFQSSIsIm9wZW5pZCIsInByb2ZpbGUiXSwiYW1yIjpbInB3ZCJdfQ.nchBSZ5gKh04v0UUDzpptcDVY80XrBfYFlGFHWhlphIkFHgejNFb6z8bW01Uu_ESGAwhV-ZR_fTWPtO9S28YkeG4Mq78LBBdbhYPe2mzx6FSBkrFaCZ3uYZ_UxmaFdGXCocuAudJp2Wk6OFucTPLFphpP9OkedoyCsugwqeAR1H97iA5kwjMxPwRJZrjVoL8hVuNSjf7OvxivqGaGYtBjDCjR92zcHG_lbLJ-5B0y8b2TsvhESMSuev2RT8DDDFa6q1s8H7mO7-gepArtgn26LqFqTCVC4aiNB0NCtcY6biXhgrDUAxyioeWxV9NyEV2FzDyY41a0WXyUfg9DiytGw
